-- ============================================================
-- Target Store: Estem Temi Zli K Ve Endustri Yel Urunler (estem-temi-zli-k-ve-endustri-yel-urunler)
-- Generated at: 2026-05-26 01:39:10
-- Scraped: 37 products, 1 categories
-- ============================================================

DO $$
DECLARE
    v_store_id uuid;
BEGIN
    -- 1. UPSERT STORE
    INSERT INTO stores (slug, name, tagline, logo_url, phone, address, category_order, carousel_data, announcement_bar)
    VALUES ('estem-temi-zli-k-ve-endustri-yel-urunler', 'Estem Temi Zli K Ve Endustri Yel Urunler', 'Estem Endüstriyel Temizlik Ürünleri', 'http://estemtemizlik.com/site_document/files/resim/logoestem_02058.png', '+908508882096', 'İstoç Tic. Merkezi 34. Ada No:72 Bağcılar / İSTANBUL', '["Temizlik Hizmetleri"]'::jsonb, '{"enabled": false, "slides": []}'::jsonb, '{"text": "📦 Estem Temi Zli K Ve Endustri Yel Urunler B2B Sipariş ve Talep Kataloğu Yayında!", "enabled": true}'::jsonb)
    ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        tagline = EXCLUDED.tagline,
        logo_url = EXCLUDED.logo_url,
        phone = EXCLUDED.phone,
        address = EXCLUDED.address,
        category_order = EXCLUDED.category_order,
        carousel_data = EXCLUDED.carousel_data,
        announcement_bar = EXCLUDED.announcement_bar;

    SELECT id INTO v_store_id FROM stores WHERE slug = 'estem-temi-zli-k-ve-endustri-yel-urunler';

    -- 2. RESET EXISTING PRODUCTS
    DELETE FROM prods WHERE store_id = v_store_id;

    -- 3. INSERT PRODUCTS
    INSERT INTO prods (store_id, name, category, image_url, description, price) VALUES
        (v_store_id, 'Ürünlerimiz', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/urun_img/2QA1GJQLT_resim_23_8_2022_16_s.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Çamaşır ve Çöp Toplama', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM -TEK BRANDALI - 3 KATLI - 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/E4BQTKPOT_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'GALVENİZE SET', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/C5NIARX21_resim_10_9_2019_15_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'CAM BEZİ-PARLAK 40*40', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/90V14OPO2_resim_9_1_2023_14_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM - BRANDALI - TEMİZLİK SETLİ - 3 KATLI - 4 KOVA', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/ZAL9YOX04_resim_23_8_2022_12_b.jpg', 'Komple set halinde pek çok ihtiyaca cevap verecek olan krom kat arabaları, arkada çamaşır veya çöp torbası kullanımı yeri, önde 2x20L kapasiteli kova ve presten oluşan temizlik seti ve ortada bulunan 3 raf ile üstteki 4 renkli 6L kova sayesinde çok farklı alanlarda pratik kullanım imkanı sunar.', '0'),
        (v_store_id, 'Mutfak Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM TEMİZLİK SETLİ - 3 KATLI - 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/1P2RQSIYZ_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM -ÇİFT BRANDALI - 2 KATLI - 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/63OBKUKFV_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KATALOG', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/files/resim/_thumbs/1585815249_01059.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'PLASTİK KAT HİZMET ARABASI-TEK BRANDALI-3 KATLI-4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/765ISXH0A_resim_23_8_2022_16_b.jpg', 'Yeniden kurulabilir plastik taşıyıcı & boyalı metal dik şase, 1x Plastik kapaklı çamaşır/çöp için PVC torba, 4x renk kodlu 6L. kova & 2x havuzlu raf, Sap tutuculu mop standı & kaygan zemin levhası için askı, 4x Metal/kauçuk malzemeli bilyalı ekstra teker. (2’si frenli)', '0'),
        (v_store_id, 'Genel Temizlik', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM - BRANDALI - TEMİZLİK SETLİ- 4 KOVA-DOLAPLI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/NN8NJ0JSV_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Aparat Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'PLASTİK KAT HİZMET ARABASI-TEMİZLİK SETLİ-3 KATLI-4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/3OWXTV3RA_resim_23_8_2022_16_b.jpg', 'Yeniden kurulabilir plastik taşıyıcı & boyalı metal dik şase, 2x 16L. Ekstra plastik kova, EKSTRA pres (CYP 3326), 4x renk kodlu 6L. ayrışım kovasi & 2x havuzlu raf, Sap tutuculu mop standı & kaygan zemin levhası için askı, 4x Metal/kauçuk malzemeli bilyalı ekstra teker. (2’si frenli)', '0'),
        (v_store_id, 'HİJYENİK KLOZET SİSTEMİ (ELEKTRİKLİ)', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/SNFI0DK28_resim_10_9_2019_14_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'CAM BEZİ-BAKLAVA DESEN 40*40', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/S2JFN21ZF_resim_9_1_2023_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Klozet Sistemleri', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Hijyen Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'İLETİŞİM', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'CAM KAZIMA JİLETİ', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/FBDSOX4UA_resim_11_9_2019_15_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'PLASTİK KAT HİZMET ARABASI DOLAPLI-ÇİFT BRANDALI-4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/RZFA5VAEY_resim_23_8_2022_16_b.jpg', 'Yeniden kurulabilir plastik taşıyıcı & boyalı metal dik şase, 2x Plastik kapaklı çamaşır/çöp için PVC torba, 4x renk kodlu 6L. kova & 2x havuzlu raf,Sap tutuculu mop standı & kaygan zemin levhası için askı, 4x Metal/kauçuk malzemeli bilyalı ekstra teker. (2’si frenli)', '0'),
        (v_store_id, 'Bez Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Çamaşır Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'HİJYENİK RULO', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/EFYVCDOOX_resim_10_9_2019_14_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Temizlik Setleri', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/urun_img/V37HSBXD9_resim_11_9_2019_15_s.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'PLASTİK KAT HİZMET ARABASI-ÇİFT BRANDALI-3 KATLI-4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/19FN3EFUH_resim_23_8_2022_16_b.jpg', 'Yeniden kurulabilir plastik taşıyıcı & boyalı metal dik şase, 2x Plastik kapaklı çamaşır/çöp için PVC torba, 4x renk kodlu 6L. kova & 2x havuzlu raf,Sap tutuculu mop standı & kaygan zemin levhası için askı, 4x Metal/kauçuk malzemeli bilyalı ekstra teker. (2’si frenli)', '0'),
        (v_store_id, 'Çöp Kovaları', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/urun_img/9AAWSK457_resim_25_9_2019_21_s.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM -ÇİFT BRANDALI - DOLAPLI- 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/2Z7NIH9EE_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Kağıt Grubu', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/urun_img/I8YYRCHPM_resim_10_9_2019_21_s.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABALARI', 'Temizlik Hizmetleri', 'http://estemtemizlik.com/site_document/urun_img/2NLWA7GXC_resim_6_8_2020_13_s.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI YEDEK KOVA', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/FM37AYNNH_resim_23_8_2022_12_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM -TEMİZLİK SETLİ- DOLAPLI- 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/0OS3F86WA_resim_23_8_2022_13_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'ÇİFT KOVALI METAL PRESLİ TEMİZLİK SETİ', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/TEXLVG9CA_resim_10_9_2019_15_b.jpg', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'KAT HİZMET ARABASI KROM -TEK BRANDALI - DOLAPLI - 4 KOVALI', 'Temizlik Hizmetleri', 'http://www.estemtemizlik.com/site_document/urun_img/NGRGUJ6QI_resim_23_8_2022_13_b.jpg', 'Arkada bir adet çamaşır veya çöp torbası kullanımı yeri ve önde bulunan kilitli raflı dolap modülü ile üstteki 4 renkli 6L kova sayesinde dar alana sahip konaklama ve yeme/içme hizmeti veren işletmelerde pratik kullanım imkanı sunar.', '0'),
        (v_store_id, 'Sarf Malzeme Grubu', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0'),
        (v_store_id, 'Çöp Poşetleri', 'Temizlik Hizmetleri', 'https://hemencdn.com/interface/global/images/flags/platinum/it.png', 'Firmamız, Endüstriyel Temizlik Malzemeleri konusunda faaliyet göstermektedir. Farklı sektörlerde bir çok kurum ile çalışan firmamızın en önemli mesuliyeti, kalite, iyi hizmet ve müşteri memnuniyeti olup, devamını sağlamaktır.', '0');
END $$;
